// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDsAdT97ypxZmDz-hQXAWSQ8dP3RVR_Q',
    appId: '1:476556544507:android:3de41d31776170e6a8635e',
    messagingSenderId: '476556544507',
    projectId: 'bahandi-etry',
    storageBucket: 'bahandi-etry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXEhoQe8nisNiaSMLOJQCbQyVLKEXLJo',
    appId: '1:476556544507:ios:903e4d2607e155c2a8635e',
    messagingSenderId: '476556544507',
    projectId: 'bahandi-etry',
    storageBucket: 'bahandi-etry.firebasestorage.app',
    iosBundleId: 'com.etry.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6EL3avackKL26FHjmn6g1mB4v6ciHOpg',
    appId: '1:476556544507:web:6ed415371796ac16a8635e',
    messagingSenderId: '476556544507',
    projectId: 'bahandi-etry',
    authDomain: 'bahandi-etry.firebaseapp.com',
    storageBucket: 'bahandi-etry.firebasestorage.app',
    measurementId: 'G-ZF4XEBPR49',
  );

}